### ISSUE TITLE
[3] Support for deploying CK8s on City Networks Compliant Cloud

### ISSUE THREAD

**Issue by tordsson** [elastisys/compliantkubernetes-kubespray#106]
Is your feature request related to a problem? Please describe.

Can we deploy ck8s using kubespray onto City Networks Compliant Cloud (OpenStack-based and _should_ be identical to City Networks Public cloud? 

Describe the solution you'd like

Determine how to deploy CK8s on City Network Compliant Cloud, with as minor differences from City Network Public Cloud (based on OpenStack) as possible. 

Describe alternatives you've considered
Does not apply.

Additional context
We (Elastisys) have business reasons why we for sure want this to work on a technical level. :)

Definition of done:
When deployment and day 2 operations effort on Compliant Cloud are similar to those for public cloud.

**Comment by pettersv** [comment]
Also update the infra provider docs, currently residing in the "petter-ip-docs" branch of ck8s-ops

**Comment by viktor-f** [comment]
I think this can be closed. I managed to setup a production cluster on the compliant cloud without any issues and Petter's docs is merged https://github.com/elastisys/ck8s-ops/tree/main/docs/infra-providers/citycloud/compliant-cloud
