### ISSUE TITLE
[1] reboot-nodes script throws an error

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-kubespray#112]
**Describe the bug**

When running the reboot-nodes script it sometimes fails when waiting for a node to come back up. The error is

fatal: [staging-sc-k8s-master-1]: FAILED! => {"msg": "The conditional check 'kubelet_heartbeat.rc == 0' failed. The error was: error while evaluating conditional (kubelet_heartbeat.rc == 0): 'dict object' has no attribute 'rc'"}

If the script is executed again it usually works for that node, but might stop on the next, requiring multiple re-runs to reboot all nodes.

**To Reproduce**
Run ./bin/ck8s-kubespray reboot-nodes [sc|wc]

**Expected behavior**
All nodes are rebooted without error

**Screenshots**

**Version (add all relevant versions):**

- Compliant kubernetes apps version [e.g. v0.8.0]
- compliantkubernetes-kubespray 

**Additional context**

**Comment by tordsson** [comment]
Add description in script of this know issue (to calm administrator using the script)
