### ISSUE TITLE
Rook ceph osd crashing

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-kubespray#121]
**What should be investigated.**
What technology/product/concept should be investigated?

Discussion in [PR](https://github.com/elastisys/ck8s-ops/pull/688) talking about that we want to know why the osd keep crashing and if there is a way to add our quick fix to be more permanent. 

**What artifacts should this produce.**
How should the knowledge gathered from this task be captured.

**Comment by cristiklein** [comment]
Please talk to the supplier and ask for a new Node. Leave a comment here if that fixed the recurring problem.

**Comment by raviranjanelastisys** [comment]
Still facing issue but waiting for few more weeks how stable it is .

**Comment by crssnd** [comment]
fixed now
