### ISSUE TITLE
[1] Add PR template and issue template

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-kubespray#13]
We lack issue templates in most(all) repositories and PR templates in some. We should add these templates to all assorted compliantkubernetes repositories and update the ones that already exists.

The templates does not have to be very elaborate but should at least include some simple list of what we expect to find in an issue/PR and a short explanation for each item.

Acceptance criteria:
Issue templates and PR templates exists for all compliantkubernetes repositories.

**Comment by cristiklein** [comment]
We are a bit unsure what the future of this repository will be. How will the repo look like in 6 months? What direction should it take?

We agree that there is a need for a "pointer to other projects" repository, but we are unsure that this repo is the answer. It could be that good documentation and a few samples repositories would render this repository obsolete.

**Comment by Xartos** [comment]
Done #33 elastisys/compliantkubernetes-apps#197
