### ISSUE TITLE
Allow for (easier) replacement of masters

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-kubespray#141]
RIght now we are using these variables in cluster.tfvars to control the provisioning of masters

```
number_of_k8s_masters_no_floating_ip = 3
number_of_k8s_masters_no_floating_ip_no_etcd = 0
flavor_k8s_master = "8a707999-0bce-4f2f-8243-b4253ba7c473"
```
However, this makes it a bit hard to replace a master in the same way we can replace a worker node, i.e. adding a new one and then removing the old.

TODO: investigate if we should swith to a similar approach for masters as with workers, i.e. list them one by one.

**Comment by OlleLarsson** [comment]
Concerns openstack terraform,

Added to needs triage due to it being a mess when a master node is broken and needs to be replaced.

**Comment by robinAwallace** [comment]
PR up for it https://github.com/kubernetes-sigs/kubespray/pull/8709.
