### ISSUE TITLE
[3]Nodes are unable to join the cluster

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-kubespray#165]
**Describe the bug**
Unable to fetch the kubeadm-config ConfigMap from cluster: failed to get node registration: failed to get node name from kubelet config: open /etc/kubernetes/kubelet.conf: no such file or directory
**To Reproduce**

I don't know if it can be reproduced. But, please checkout the latest ck8s-kubespray version, you will most likely face this error. 

**Expected behavior**
We don't want this to happen. 

**Version (add all relevant versions):**

- Compliant kubernetes version [v2.18.0]

**Additional context**
@Ajarmar suspects, it has something to do with our group_vars. Apparently, when Kubespray/inventory/sample was used, things were working just fine.

**Comment by aarnq** [comment]
I have tested setting up multiple clusters now on three different cloud providers, both using our templates and the one from the Kubespray inventory sample, using version v2.18.0-ck8s1 and I have not been able to reproduce it so I will close this.

If anyone comes across this and want to investigate it further, feel free to reopen or create a new issue with the setup you have, the steps you took and the variables you set.
