### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-kubespray#167]
**Describe the bug**
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

**To Reproduce**
Install ck8s-kubespray use version 2.18.0. and apply apps. 

**Expected behavior**
We don't want this to happen!! 

**Version (add all relevant versions):**

- Compliant Kubernetes apps version [e.g. v2.18.0]

**Additional context**
This can be solved by recreating new certs and use them as kubeconfig

**Comment by crssnd** [comment]
maybe just a one time error
