### ISSUE TITLE
[1] Change init flow to increase transparency in how  kubespray is used

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#17]
Instead of copying the whole `group_vars` folder, we should focus on only setting those variables whose value we need to change. This will not only improve adherence to the Principle of Least Astonishment (POLA), but also improve ease of maintenance moving forwards.

Relevent Ansible documentation on how variables get merged is [here](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#how-variables-are-merged).

Acceptance criteria:
* This repo only contains kubespray variables we need to change.
* Configuration files generated by `./bin/ck8s-kubespray init` only contains variables we need to change.
* `./bin/ck8s-kubespray apply` consumes an intuitive merge of kubespray defaults and the variables we overwrite.
* Update documentation (see https://github.com/elastisys/compliantkubernetes/issues/44)

**Comment by tordsson** [comment]
Closing this will fix: https://github.com/elastisys/compliantkubernetes-kubespray/issues/20
