### ISSUE TITLE
[0] openstack terraform: Make it possible to run both local and non-local flavors.

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-kubespray#174]
**Is your feature request related to a problem? Please describe.**
It is not possible to run a mix of boot from volume and local disk flavors.
This is relevant for the k8s_nodes configuration as we need to be able to do that to have a smooth migration from old to new flavors on certain cloud providers.

Also it would be good if we made it possible use cloud-init in a way that works with our way of storing the inventory. Right now you have to modify the cloud-init template file within the terraform module. This is not something that works for us.
We might need this for supporting local disk workloads in Kubernetes.

**Describe the solution you'd like**
It is possible to run both in the same inventory.

**Describe alternatives you've considered**
Not enabling this

**Additional context**
We need to be able to this do be able to migrate from local disks to boot from volume flavors.

**Definition of done:**
Title + cloud-init rework

**Comment by raviranjanelastisys** [comment]
Please do this task together with - https://github.com/elastisys/ck8s-ops/issues/2687
