### ISSUE TITLE
[5]Creating a cluster on ElastX with Kubespray 2.19

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-kubespray#199]
**What should be investigated.**

Investigate why there is an issue creating an environment on ElastX using Kubespray 2.19.

When running kubespray 2.19 on elastx I got the following error:

```
Error: Error creating OpenStack server: Bad request with: [POST https://ops.elastx.cloud:8774/v2.1/servers], error message: {"badRequest": {"code": 400, "message": "Port 16ec26fa-c530-4619-88a4-e03e60455dca requires a FixedIP in order to be used."}}
```

Not sure if this is only a problem when using the devbox but I was using devbox when I tried this.

**What artifacts should this produce.**

Find out the root cause of this error and see if there is a fix available.

**Comment by robinelastisys** [comment]
https://github.com/kubernetes-sigs/kubespray/pull/9159#event-7148037831

**Comment by crssnd** [comment]
should we add this change to our kubespray repo? I would like to be able to upgrade or install v2.19 in ElastiX before the next kubespray version
https://github.com/elastisys/kubespray/tree/ca127415a8e6b1173a4b71808e8a8c49739c258c

**Comment by raviranjanelastisys** [comment]
Discussed with @robinelastisys  , good to close now !!
