### ISSUE TITLE
[1] Default to serial execution of hosts when running the upgrade playbook

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-kubespray#208]
**Is your feature request related to a problem? Please describe.**
For some plays the serial execution is based on a percentage on the number of hosts.
For us this is not good as we want to have one node upgraded at a time

**Describe the solution you'd like**
An solution is to always pass `-e serial=1` in the `run-playbook` command 

**Describe alternatives you've considered**
Not setting this automatically and let the user be responsible for remembering to set it.

**Additional context**

**Definition of done:**
A serial execution of 1 if enforced when running the upgrade playbook

**Comment by Xartos** [comment]
Will discussing internally, since there might be some more problems with doing this

**Comment by OlleLarsson** [comment]
I think we did discuss this @Xartos and came to the conclusion that are no problems with the mentioned approach
