### ISSUE TITLE
[1] Do not fiddle with the SSH key

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#21]
To adhere to the Principle of Least Astonishment (POLA), we should simply use the SSH key to which the user points to, instead of copying around.

Acceptance criteria:
* kubespray does not require pointing to an SSH key, rather uses whatever `ssh` uses by default.
* kubespray does not copy the public SSH key into the `.state` folder.

**Comment by Xartos** [comment]
We will need to first make sure that we start using all personal keys instead of cluster keys. I don't think we have a good process for this yet, so I think we should complete that first before perusing this issue.

**Comment by cristiklein** [comment]
Good point, do you have a good forum to pick that discussion up?
