### ISSUE TITLE
[5] rook - create a helm/helmfile chart

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-kubespray#217]
**Is your feature request related to a problem? Please describe.**
At the moment we cannot have custom values for each environment with rook-ceph, and we would like to improve that for greater flexibility and customization.

**Describe the solution you'd like**
Create the same structure using helm and helmfile as we have for AMSs, so we can add custom configuration for rook. Keep rook-ceph in this repository, for now.

**Definition of done:**
- AMS line helm and helmfile configurations for the rook installation that can be customized based on value.yaml file
- try to use the [upstream charts](https://github.com/rook/rook/tree/master/deploy/charts) for that

**Comment by Xartos** [comment]
Rook now has an official helm chart for the cluster setup as well https://github.com/rook/rook/tree/master/deploy/charts/rook-ceph-cluster
So maybe that will be sufficient

**Comment by OlleLarsson** [comment]
related https://github.com/elastisys/compliantkubernetes-kubespray/issues/82

**Comment by davidumea** [comment]
I started on this and have a [branch](https://github.com/elastisys/compliantkubernetes-kubespray/tree/david/add-helm-chart-for-rook) with some structural setup, feel free to use or base on this branch.
