### ISSUE TITLE
[2] Cloud provider documentation

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#23]
There is no mention of cloud provider integration. To minimize the risk of bad surprises it would be good to mention explicitly what to expect. I.e. either we say that it is up to the user to tweak the variables for things like this, or we actually provide config that does this and mention it in the docs.

Definition of done: The readme has a note regarding what to expect with the default values from this repo, and an example of how to edit the variables.

Bonus: Sample configuration for each cloud provider. Upon init, the relevant sample is used to generate the defaults so that we automatically get cloud provider integration.

**Comment by cristiklein** [comment]
It is currently unclear how our documentation would complement [CKA](https://www.cncf.io/certification/cka/). We need to re-evaluate this task at a later time.

**Comment by cristiklein** [comment]
Having re-interpreted this task, it seems that this is already done: https://github.com/elastisys/compliantkubernetes-kubespray/tree/main/config.

@viktor-f Will update the text in the README to reflect this:

> flavor will determine some default values for a variety of config options. Supported options are default.
