### ISSUE TITLE
Try enabling NTP service

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-kubespray#244]
**What should be investigated.**
What technology/product/concept should be investigated?

We should try out the NTP feature in kubespray and see if it works as intended.
The settings to try out can be found [here](https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubernetes/preinstall/defaults/main.yml#L69-L107)

This should include setting up multiple ntp servers (as the default seem to be)

**What artifacts should this produce.**
How should the knowledge gathered from this task be captured.

* Investigation documentation about how it works setting this up and if there were any hurdles along the way

**Comment by robinAwallace** [comment]
This should be closed right?

**Comment by Xartos** [comment]
Id say yes
