### ISSUE TITLE
[1] Add get-requirements file with standardized terraform version

### ISSUE THREAD

**Issue by Ajarmar** [elastisys/compliantkubernetes-kubespray#248]
**Is your feature request related to a problem? Please describe.**
To avoid inconsistencies because of differing terraform versions, it would be preferable to have it standardized.

**Describe the solution you'd like**
Add a `get-requirements.yaml` file that downloads and installs a specific version of terraform. See [the apps repo](https://github.com/elastisys/compliantkubernetes-apps/blob/main/get-requirements.yaml) for an example.

**Describe alternatives you've considered**

**Additional context**
Currently terraform v0.14.x works fine with kubespray, but we would like to move to a more recent version, specifically v1.3.5. However, it would have to be tested to make sure it doesn't cause any issues.

**Definition of done:**
There is a `get-requirements.yaml` that downloads and installs v1.3.5 of terraform, unless there is a good argument for a different version.

**Comment by davidumea** [comment]
We had a discussion in the office and thought it make more sense to go with terraform `1.2.9` for now, that way we don't have to make a new patch release for ck8s-kubespray to fix the experimental feature issue we ran into with terraform `1.3+`. This way we are also closer to what the upstream kubespray repo is using.
