### ISSUE TITLE
[2] Synchronize time with ntp.se

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#250]
**Is your feature request related to a problem? Please describe.**

We are looking into [MSBFS 2020:7](https://www.msb.se/siteassets/dokument/regler/forfattningar/msbfs-2020-7-foreskrifter-om-sakerhetsatgarder-i-informationssystem-for-statliga-myndigheter.pdf). The only deviation we found is that we need to synchronize our clocks to `ntp.se` (see more details [here](https://www.ntp.se)).

**Describe the solution you'd like**

Please add some Ansible magic to make sure that Compliant Kubernetes synchronizes to UTC(SP) by default. Please follow Section 2 in [this best practices guide](https://www.netnod.se/blog/best-practices-connecting-ntp-servers). Do not include non-Swedish NTP servers.

**Describe alternatives you've considered**

* `ntp.org`
* Whatever Ubuntu provides by default.

None of these solutions conform to MSBFS 2020:7.

**Additional context**

Here is the exact text of the regulation:

> 4 kap.
>
> Korrekt och spårbar tid
> 13 § Myndigheten ska använda robust och korrekt tid spårbar till den svenska tillämpningen av koordinerad universell tid, UTC(SP), i sin produktionsmiljö.
>
> Allmänna råd
> ..Myndigheten bör använda tidstjänsten Swedish Distributed Time Service på
www.ntp.se. Behovet av att använda robust och korrekt tid spårbar till den svenska tillämpningen av koordinerad universell tid, UTC (SP) i utvecklings-, test- och utbildningsmiljö bör identifieras och hanteras.

**Definition of done:**

- Compliant Kubernetes synchronizes with `ntp.se` according to best practices by default.

**Comment by cristiklein** [comment]
I wrote an [Ansible role that does the trick](https://github.com/cristiklein/stateless-workstation-config/tree/master/roles/cklein.ntp.se).

**Comment by Xartos** [comment]
Since you need to use the kubespray settings for this we might as well include this investigation here https://github.com/elastisys/compliantkubernetes-kubespray/issues/244

**Comment by cristiklein** [comment]
Nice find! I wasn't aware that Kubespray already includes a feature for configuring NTP.

I agree that this issue can be merged into #244. Shall I do that, or do we just "mentally" merge them? :smile:

**Comment by Xartos** [comment]
Mentally is fine I would say
