### ISSUE TITLE
Use kubernetes as datastore for calico

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#26]
As per [this issue](https://github.com/kubernetes-sigs/kubespray/issues/6687), kubernetes datastore is the recommended setting for `calico_datastore` and the new default in kubespray. On the version we currently have, etcd is still the default and I'm unable to get this to work together with `etcd_kubeadm_enabled: true`.

Definition of done: `calico_datastore: kdd` is set in the group_vars generated when we run init.

Note: Since this is the default in v2.15, we can close this issue once #18 is done.

**Comment by OlleLarsson** [comment]
#18 has been merged so i guess we can close this issue?

**Comment by Xartos** [comment]
Right, yes. I was suppose to do that
