### ISSUE TITLE
Support Exoscale cloud controller manager

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#27]
Exoscale [now has a cloud controller manager](https://www.exoscale.com/syslog/exoscale-kubernetes-cloud-controller-manager-release/) for Kubernetes. We should make use of it to get better integration with the platform. It currently supports Service of typ `LoadBalancer` and may add more things in the future.

**Comment by tordsson** [comment]
Future Block storage support in cloud provider would make this more worth it.
