### ISSUE TITLE
Include calico MTU for known providers

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#29]
We don't specify MTU for calico in our flavors.
However, since we know what the values should be on all clouds that we support, it would make sense to add it.
For bare metal it would be nice with a note that this value may need changing.

Acceptance criteria: MTU is set for all clouds we support and a note (in readme or terminal output) points the operator to this setting if we don't know what the value should be.

**Comment by cristiklein** [comment]
I appreciate the attention to details, but, honestly, until a customer complains about network performance, changing the MTU from the default 1500 feels overkill. :smile:

**Comment by OlleLarsson** [comment]
I think that we encoutered a bug when using 1500.
If it was on safespring or some application like harbor I honestly don't remember.
You remember this @viktor-f ?

**Comment by Xartos** [comment]
If you use calico IPinIP you should change it. Otherwise **wierd** errors will appear.
See https://docs.projectcalico.org/networking/mtu#determine-mtu-size

**Comment by cristiklein** [comment]
Hmm ... I was operating under the assumption that we use Calico without encapsulation, i.e., IP-over-Ethernet directly.

**Comment by Xartos** [comment]
Nope, the default in calico is ipip and that's what we use. It's also very nice since we don't need to assume anything of the underlying network.
