### ISSUE TITLE
[5] Demonstrate Compliant Kubernetes on Azure

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#3]
Please demonstrate that we can run Compliant Kubernetes on Azure via the following tech stack:

1. Default cloud image available on Azure
2. Some Azure Terraform script
3. Kubespray
4. Rook
5. compliantkubernetes-apps

# Acceptance criteria
We have evidence for Compliant Kubernetes working on Azure, specifically:
- Sample repository capturing the exact steps and versions of all tools used, potentially via git submodules.
  - Please plan for the repo to become publicly available.
- Screenshots of:
  - Azure Portal
  - Workload cluster content (e.g., kubectl get all --all-namespaces)
  - Service cluster content (e.g., kubectl get all --all-namespaces)
  - Sample application working in the browser (e.g., https://github.com/bitnami/charts/tree/master/bitnami/wordpress)
    - Kibana (application log and Kubernetes audit log)
    - Grafana
    - Harbor with some image being pushed and scanned

**Comment by tordsson** [comment]
Also fixes: https://github.com/elastisys/compliantkubernetes-kubespray/issues/43

**Comment by llarsson** [comment]
Closing due to https://github.com/elastisys/compliantkubernetes/pull/68 getting merged.
