### ISSUE TITLE
[2] Detailed server groups for control plane nodes

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-kubespray#305]
**Is your feature request related to a problem? Please describe.**
Currently all control plane nodes in a cluster will be added to the same server group. Not all clouds support having more than 3 nodes in a server group. This is then inconvenient if we ever need to replace the control plane nodes in a cluster since we will need to replace the nodes one by one, which takes a while to do.

**Describe the solution you'd like**
Add the possibility to control what server group each control plane node is added to, similar to what is possible for worker nodes. Then we could create a new server group if we ever need to replace control plane nodes.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
It is possible to control the server groups for control plane nodes.

**Comment by simonklb** [comment]
@viktor-f from what I could tell, not all infrastructure providers have the concept of server groups, would you mind specifying which providers this issue targets?

**Comment by viktor-f** [comment]
This was mainly targeted at the openstack providers we work with and thus the openstack terraform code. Not sure about the status of server groups in upcloud, but perhaps that could use the same fix.

**Comment by simonklb** [comment]
> This was mainly targeted at the openstack providers we work with and thus the openstack terraform code. Not sure about the status of server groups in upcloud, but perhaps that could use the same fix.

Looks like server groups for control plane nodes already is supported in the UpCloud Terraform configuration: https://github.com/kubernetes-sigs/kubespray/commit/5bb54ef6a217aaeb56e5b9a9a89e8a3b6929e0ae @robinAwallace could you confirm?

**Comment by robinAwallace** [comment]
> > This was mainly targeted at the openstack providers we work with and thus the openstack terraform code. Not sure about the status of server groups in upcloud, but perhaps that could use the same fix.
> 
> Looks like server groups for control plane nodes already is supported in the UpCloud Terraform configuration: [kubernetes-sigs/kubespray@5bb54ef](https://github.com/kubernetes-sigs/kubespray/commit/5bb54ef6a217aaeb56e5b9a9a89e8a3b6929e0ae) @robinAwallace could you confirm?

Yes UpCloud have server groups. I have also added, but merged, strict anti-affinity.

**Comment by OlleLarsson** [comment]
> Is this something we should add support for or is my time better spent elsewhere?

I'm putting words in Viktor's mouth here, but unless it's something that can be done rather quick, your time is better spent elsewhere since we have no MS customers left on exoscale (or even projected to my knowledge).

**Comment by simonklb** [comment]
> > Is this something we should add support for or is my time better spent elsewhere?
> 
> I'm putting words in Viktor's mouth here, but unless it's something that can be done rather quick, your time is better spent elsewhere since we're not working towards exoscale support atm.

Thanks, I'll leave Exoscale untouched for now then and consider this issue done when the OpenStack control plane server group support is merged.

**Comment by simonklb** [comment]
Seeing how we are moving towards Cluster API spending time on trying to getting this merged upstream feels less of a priority. If someone disagrees feel free to reopen the issue!
