### ISSUE TITLE
Upgrade no longer handles custom cluster prefix

### ISSUE THREAD

**Issue by Elias-elastisys** [elastisys/compliantkubernetes-kubespray#311]
**Describe the bug**
All Kubespray functionality has up to this point handled any name/prefix to the cluster naming.

When we run multi wc to one sc we named the clusters `wc-staging` and `wc-prod` to avoid confusion, but the new automated upgrade steps seem to have hardcoded the naming to just `wc` and `sc`

The docs still seem to indicate that you can initialize an environment with any prefix.

**To Reproduce**

1. Initialize an environment with a name other than just `wc` and `sc` 
1. Try to run `ck8s-kubespray upgrade v2.22 prepare`
1. See error

**Expected behavior**
I would expect the CLI to still work with any naming as before.

Or the removal of docs indicating that a custom name can be used.

**Version (add all relevant versions):**

- Compliant kubernetes kubespray version v2.21.0 

**Additional context**

**Comment by crssnd** [comment]
closing in favour of https://github.com/elastisys/compliantkubernetes-kubespray/issues/314
