### ISSUE TITLE
Thoughts on adding support for Azure ?

### ISSUE THREAD

**Issue by anwarchk** [elastisys/compliantkubernetes-kubespray#312]
**Is your feature request related to a problem? Please describe.**
Currently the option to init doesn't accept `azure` as a value. Are there plans to support Azure ?

**Describe the solution you'd like**
Just like GCP and AWS, Azure is supported as a cloud provider value to init.

**Comment by cristiklein** [comment]
Duplicate of https://github.com/elastisys/compliantkubernetes/issues/666 

Closing.
