### ISSUE TITLE
[3] contrib/tf/upcloud: add usage of routers

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-kubespray#333]
**Is your feature request related to a problem? Please describe.**
UpCloud has the concept of routers which allows private networks to be connected together but also enables DHCP(?).
The usage of routers is necessary for us to be able to transfer data to and from their new managed object storage service via the internal/private network.

In addition to this we want to check the possibility of replacing the Gateway VM with the [VPN Gateway](https://upcloud.com/docs/products/networking/features/gateways/) at UpCloud.
The benefits here is that we would not need to be responsible for the gateway VM. The downsides would be that it only supports IPSec.

**Describe the solution you'd like**
Include the creation and configuration of router(s) as needed via the Terraform contrib module for UpCloud.

**Describe alternatives you've considered**
Not using routers

**Definition of done:**

- The Terraform module includes the option to setup up a router
- The possibility to enable the VPN gateway with multiple connections and configurable routes

**Comment by Xartos** [comment]
https://github.com/elastisys/compliantkubernetes-kubespray/blob/v2.25.0-ck8s3/changelog/2.25.0.md#v2250-ck8s2
