### ISSUE TITLE
[1] kube_config is not copied to config dir

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-kubespray#37]
**Describe the bug**
After kubespray has completed creating a cluster, admin.conf should be copied to .state/kube_config_[cluster].yaml However, currently this gives an error due to the .state directory not existing.

**To Reproduce**
This happens during the ./bin/ck8s-kubespray apply $CLUSTER stage

**Expected behavior**
the kube_config files should be available in the .state dir

**Comment by cristiklein** [comment]
This should be unnecessary once [ADR 0006 "Use Standard Kubeconfig Mechanisms"](https://github.com/elastisys/compliantkubernetes/blob/adr-kube-context/docs/adr/0006-use-standard-kubeconfig-mechanisms.md) is approved and implemented.
