### ISSUE TITLE
[1] Enable calico metrics reporting

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-kubespray#42]
**Is your feature request related to a problem? Please describe.**
To be able to debug kubernetes networking it would be nice to have some metrics related to calico. 

**Describe the solution you'd like**
[By default prometheus metrics are disabled](https://github.com/kubernetes-sigs/kubespray/blob/4cc065e/roles/network_plugin/calico/defaults/main.yml#L46). It can be enabled by setting the variable `calico_felix_prometheusmetricsenabled` to `true` for all in the group `k8s-cluster`.

We would also need to create a servicemonitor for this endpoints and add a grafana dashboard to visualize the data 
Maybe [this](https://grafana.com/grafana/dashboards/3244) or [this](https://grafana.com/grafana/dashboards/12175) 
*(this is another issue for https://github.com/elastisys/compliantkubernetes-apps though)*.

**Describe alternatives you've considered**
Alternatively we can choose to not expose these metrics.

**Additional context**
No

**Definition of done:**
When a new cluster is setup, calico should report metrics on all nodes.

**Comment by cristiklein** [comment]
Maybe not easy to answer by skimming through docs, but is this supporting https://github.com/elastisys/compliantkubernetes-apps/issues/165 ?

**Comment by viktor-f** [comment]
> Maybe not easy to answer by skimming through docs, but is this supporting [elastisys/compliantkubernetes-apps#165](https://github.com/elastisys/compliantkubernetes-apps/issues/165) ?

I started to look at that issue yesterday and the short answer seems to be no. Will post some more thorough findings in that issue or on slack later today.

**Comment by tordsson** [comment]
Calico's suggested Grafana dashboard: https://docs.projectcalico.org/maintenance/monitor/monitor-component-visual

**Comment by raviranjanelastisys** [comment]
Felix does export some of the calico metrics with Prometheus - The metrics collected listed  here - https://docs.projectcalico.org/reference/felix/prometheus , but not sure which metrics will help our purpose . Anyone interested can query to my test cluster - http://20.84.32.108:9090

![image](https://user-images.githubusercontent.com/75951259/119668971-efc3d700-be37-11eb-92e2-e022d2e8c5af.png)

Checking with grafana integrations

**Comment by raviranjanelastisys** [comment]
Fredrik Liv Comments -  "I don't think these are exactly the kind of metrics that I thought of when I wrote the issue, but I still think that these metrics would help in a situation where calico itself are experiencing issues."
