### ISSUE TITLE
Ingress configuration on Azure

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-kubespray#43]
**What should be investigated.**

How to configure Ingresses on the cloud environment mentioned in the title. 

See related information:

- #25, the epic from which this issue stems, and
- [ADR 0008](https://compliantkubernetes.io/adr/0008-use-hostnetwork-or-loadbalancer-for-ingress/) of Compliant Kubernetes

**What artifacts should this produce.**

Information that shall be posted as part of the "Operator Manual" on compliantkubernetes.io, so in the [compliantkubernetes](https://github.com/elastisys/compliantkubernetes) repo.

For the clouds that have an appropriate "Operator Manual" already, cloud-specific information should go in there. Use ADR 0008 for general guidance, and please do refer to it in your text, but make a cloud-specific version of the information so that a reader has all the help they could possibly want for operating Compliant Kubernetes in the environment.

For the clouds that do not yet have such a manual, add the information in new files in individual branches in the compliantkubernetes repo. So when somebody writes about, e.g., City Cloud (currently lacking an "Operator Manual"), they can just also include the info from the "load-balancing-on-city-cloud.md" file, and then delete the file.

**Comment by llarsson** [comment]
Closed because it is unclear if this is needed once https://github.com/elastisys/compliantkubernetes/pull/59 gets merged.

**Comment by vanneback** [comment]
I think this one should be opened for now. For example we have no initiation in compliantkubernetes-apps for Azure. So either some code needs to be added to the apps repository or at least documentation for what values to set in config.

**Comment by vanneback** [comment]
Finilized testing on this. It works if configured with service loadbalancer
```yaml
nginxIngress:
  hostNetwork: false
service: true
type: LoadBalancer
```
However the installation of the cluster on azure and the cloud controller integration was tricky and is not up to date to our own instructions (which are still work in progress). 

Either we need to add Azure as an init option in ck8s-apps, I think this is the desired option.
Or we need to add documentation on how to configure it on azure manually

**Comment by llarsson** [comment]
Wonderful that you have done this investigation and verified that you can get it working in this manner!

I think the appropriate next action in this case is to create an issue for "Azure init option" and see how that prioritizes against other issues, with links back to this issue and the related one you opened in Kubespray (https://github.com/kubernetes-sigs/kubespray/issues/7288).

I know @ewnetu is working on an Operator Manual documentation for Azure, so there may or may not be overlap with these efforts. @ewnetu, please synchronize with @vanneback.

**Comment by vanneback** [comment]
Related elastisys/compliantkubernetes-apps#248

**Comment by vanneback** [comment]
Putting this issue on hold until elastisys/compliantkubernetes-kubespray#3

**Comment by tordsson** [comment]
Closing this issue (deemed obsolete as of now).
