### ISSUE TITLE
[2] Support deployment of K8s on VMware vSphere using kubespray

### ISSUE THREAD

**Issue by jakubkrzywda** [elastisys/compliantkubernetes-kubespray#49]
**Is your feature request related to a problem? Please describe.**
Currently kubespray does not provide terraform scripts for VMware vSphere.

**Describe the solution you'd like**
Kubespray should support deployment on VMware vSphere by providing appropriate terraform scripts.

**Describe alternatives you've considered**
N/A

**Additional context**
Implementation of this feature will allow us to easily deploy CK8s on top of VMware vSphere.

**Definition of done:**
Kubespray successfully installs K8s cluster on VMware vSphere.

**Comment by llarsson** [comment]
Excellent! Will you make the corresponding issue and subsequent PR over at kubespray, too? :)

**Comment by llarsson** [comment]
From an internal Slack conversation, it seems like this may be considered "Done". 

@jakubkrzywda, please confirm.

**Comment by llarsson** [comment]
Link to the PR at kubespray (which is now merged) https://github.com/kubernetes-sigs/kubespray/pull/7306
