### ISSUE TITLE
Add cert-manager as kubespray addon and make cert-manager optional in apps

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-kubespray#5]
We would like to add cert-manager to clusters using kubespray instead of compliantkubernetes-apps.

This requires some testing and configuring of kubespray. It also requires us to add an option to disable the installation of cert-manager in compliantkubernetes-apps. We do not want to remove cert-manager from apps since we want compatability with clusters that are not created by kubespray.

Acceptance criteria:
- I can choose if I want to install cert-manager using compliantkubernetes-kubespray.
- I can choose if I want to install cert-manager using compliantkubernetes-apps.

**Comment by cristiklein** [comment]
Right now, there is an [ongoing discussion in Kubespray](https://github.com/kubernetes-sigs/kubespray/issues/6400). The current perception is that kubespray addons are a crappier and less maintained version of their Helm Charts counterpart. However, how "bare" should be the cluster that kubespray creates is still open. E.g., should the user install the out-of-tree cloud controller and storage provider?

CK will engage with the community and follow their discussion. For now, we opt against kubespray addons until the dust settles upstream.

**Comment by cristiklein** [comment]
Given feedback from the community, it seems like the kubespray project will rather move away from addons. It would also be more strategic for us to have more addons in our repo, so that we can target other vanilla Kubernetes clusters, such as those created via `kops` or via a managed service.
