### ISSUE TITLE
Investigate how to run on terraform cloud

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-kubespray#52]
**What should be investigated.**
Since kubespray doesn't come with terraform scripts with remote backend, we need to investigate how we should share our terraform state.

**Suggested investigations**

One way would be to write a "remote wrapper" that uses the kubespray terraform as a module like this (openstack as an example):
```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "out-organization"

    workspaces {
      name = "cluster" # Either name or prefix
    }
  }
}

module "openstack" {
  source = "../../kubespray/contrib/terraform/openstack"

  # Pass all variables down
  cluster_name = var.cluster_name
  az_list = var.az_list
  az_list_node = var.az_list_node
  .
  .
  .
}
```

And copy (or link?) the `variables.tf` in kubespray terraform

Another way would be to have the tfstate in the config repo (encryped maybe)

Or try to upstream remote backent _(I doubt this will be possible)_

**What artifacts should this produce.**
After the investigation a document with pros and cons for different solutions should be created and discussed.

**Comment by cristiklein** [comment]
I was operating under the assumption that Terraform is happy to take [backend configuration via the command line](https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration).

I'm pasting here an example for convenience:

```
$ terraform init \
    -backend-config="address=demo.consul.io" \
    -backend-config="path=example_app/terraform_state" \
    -backend-config="scheme=https"
```

If I am right (note the "if" I haven't fully tested this), then using Terraform Cloud should be as easy as updating the documentation.

**Comment by Xartos** [comment]
From the same document

> When using partial configuration, Terraform requires at a minimum that an empty backend configuration is specified in one of the root Terraform configuration files, to specify the backend type

**Comment by Xartos** [comment]
So my example could be reduced to

```hcl
terraform {
  backend "remote" {}
}

module "openstack" {
  source = "../../kubespray/contrib/terraform/openstack"

  # Pass all variables down
  cluster_name = var.cluster_name
  az_list = var.az_list
  az_list_node = var.az_list_node
  .
  .
  .
}
```

Then you can use the cli to fill the content of the backend block.

**Comment by cristiklein** [comment]
This sucks. Seems like you can configure the Terraform backend, but not **select** the Terraform backend from the configuration.

Another approach would be to "append" a `backend.tf` as follows:

```
cklein@minitrue:~/kubespray/inventory/my-exoscale-cluster/tf$ ls -l
total 8
-rw-rw-r-- 1 cklein cklein  118 feb 19 16:11 backend.tf
-rw-rw-r-- 1 cklein cklein 1365 feb 19 15:00 default.tfvars
lrwxrwxrwx 1 cklein cklein   43 feb 19 16:12 main.tf -> ../../../contrib/terraform/exoscale/main.tf
lrwxrwxrwx 1 cklein cklein   43 feb 19 16:12 modules -> ../../../contrib/terraform/exoscale/modules
lrwxrwxrwx 1 cklein cklein   45 feb 19 16:12 output.tf -> ../../../contrib/terraform/exoscale/output.tf
lrwxrwxrwx 1 cklein cklein   45 feb 19 16:12 templates -> ../../../contrib/terraform/exoscale/templates
lrwxrwxrwx 1 cklein cklein   48 feb 19 16:12 variables.tf -> ../../../contrib/terraform/exoscale/variables.tf
lrwxrwxrwx 1 cklein cklein   47 feb 19 16:12 versions.tf -> ../../../contrib/terraform/exoscale/versions.tf
```

I'll ponder about the pros and cons.

**Comment by cristiklein** [comment]
After sleeping over it a bit and I now favor @Xartos 's first solution. The configuration of each environment would include "top-level" Terraform scripts that re-use upstream Kubespray modules. The top-level configs would configure the remote backend and decide the number and configuration of the clusters. (E.g., 1x service cluster of size X, 2x workload clusters of size Y).

The potential issue is that the `generate-inventory`-like scripts from Kubespray might no longer work.

To be investigated.

**Comment by tordsson** [comment]
Deprecated
