### ISSUE TITLE
Move Storage Providers to compliantkubernetes-kubespray

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#59]
**Is your feature request related to a problem? Please describe.**
We use Rook for cloud providers that doesn't have block storage support for Kubernetes, but it is a separate step not part of compliantkubernetes-apps. This makes it unnecessarily hard to set up clusters and it is easy to miss the extra step.

**Describe the solution you'd like**
Rook should be handled similar to the nfs-client-provisioner that can be enabled or disabled in the compliantkubernetes-apps config. It would fit nicely in the bootstrap stage since it is quite fundamental for many other applications.

**Describe alternatives you've considered**

- Wait for "the new configuration". This may make this issue obsolete, but it is unclear when it will arrive.
- Move all bootstrap operations to compliantkubernetes-kubespray. There is already a script for installing Rook in there, so we could move the other bootstrap components there as well. However, this seems like a like a lot of work with potential for many problems.

**Additional context**

**Definition of done:**
Rook can be enabled in the same way as the other "storage classes" when installing complienatkubernetes-apps. This would install Rook and set up a storage class as well.

**EDIT:** This issue is now the other way around. Keep Rook here and move the other storage classes, plugins, providers here from apps.

**Comment by cristiklein** [comment]
We decided to keep the storage providers in the Kubespray repo, to have a clear separation between the use-cases where we need to setup a functional, vanilla Kubernetes cluster, and the use-cases where we harden Kubernetes clusters. Hence, the Storage Providers should be assumed to be already present when the apps are applied.
