### ISSUE TITLE
Upstream KUBECONFIG handling to Kubespray

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#63]
**Is your feature request related to a problem? Please describe.**

Kubespray is missing support for producing an OpenID-based KUBECONFIG. We currently work around this [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/bin/user-kubeconfig.bash).

**Describe the solution you'd like**

* Use said mechanism in Compliant Kubernetes.

**Describe alternatives you've considered**

Keep our workaround.

**Definition of done:**

* A mechanism to produce OpenID-based KUBECONFIG exists in Kubespray master.
* Compliant Kubernetes uses said mechanisms.

**Comment by cristiklein** [comment]
An earlier version of this issue also requested for improving the non-OpenID KUBECONFIG generated by Kubespray to facilitate its usage from the local machine (i.e., proper contexts, proper usernames, proper API IP). However, we decided against this. In break-glass scenarios, just SSH into one of the masters and use `/etc/kubernetes/admin.conf` directly.

**Comment by OlleLarsson** [comment]
@cristiklein still relevant?
