### ISSUE TITLE
Demonstrate multi-AZ deployment

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#64]
**What should be investigated.**

Disaster recovery and high redundancy is on everyone's mind. Show us how to set up Compliant Kubernetes so that it can tolerate a datacenter on fire. Use [KeyCDN](https://www.keycdn.com/) to front it.

**What artifacts should this produce.**

* Deploy Compliant Kubernetes (or even a vanilla Kubernetes) cluster on your favorite EU cloud provider.
* Run in 3 AZs (or "zones" or "regions" -- terminology might vary), with 1 master per AZ and 1 worker per AZ.
* Front the Kubernetes API and Ingress with KeyCDN.
* Bonus: Ensure that traffic between the AZ are encrypted.
* Show us via a short screencast that the configuration can tolerate the failure of one AZ.

OR

* If the above is not possible, write up a concrete list of gaps.

**Comment by tordsson** [comment]
Rook deployment may cause some complications...

**Comment by tordsson** [comment]
@Pavan-Gunda did some very similar work studying k8s performance as a function of network latency for geo-decentralized setups.

**Comment by tordsson** [comment]
Initial investigations done by #93
