### ISSUE TITLE
Support for deploying CK8s on IONOS

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-kubespray#67]
**Is your feature request related to a problem? Please describe.**

IONOS offers a very good cloud platform, and they have a managed Kubernetes offering that can integrate with their load balancing and dynamic storage provisioning service. Can we offer a similarly fully-featured CK8s installation?

**Describe the solution you'd like**

Determine how to deploy CK8s and make full use of the cloud services by IONOS, including load balancing and dynamic storage. If not possible to integrate with their services, determine why. 

**Describe alternatives you've considered**

Does not apply.

**Additional context**

We (Elastisys) have business reasons why we for sure want this to work on a technical level. :)

**Definition of done:**

When one can kubespray CK8s onto IONOS VMs and have the Kubernetes experience be as seamless as possible. :) However, we are not to implement a new Kubernetes "cloud provider" or anything. See how well supported this cloud is with current tooling.

**Comment by tordsson** [comment]
Exists IONOS cloud terraform provider: https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs/resources/k8s_node_pool

**Comment by cristiklein** [comment]
Just to make sure, why do we necessarily have to go the Kubespray route, instead of setting up CK8s on top of IONOS's managed Kubernetes? (See alternative here: https://compliantkubernetes.io/operator-manual/ovh-managed-kubernetes/)

**Comment by llarsson** [comment]
There's a different ticket for that already, @cristiklein (https://github.com/elastisys/compliantkubernetes-apps/issues/336). We are looking to explore both options.

**Comment by raviranjanelastisys** [comment]
We are working on the terraform scripts to launch the VM's on the IONOS cloud , and we were able to launch VM's successfully with 1 control plane and 3 worker nodes similar to exoscale infra demo . 

Work in progress

**Comment by llarsson** [comment]
What kind of performance do you get for etcd in this setup, can you see whether the etcd component seems "happy" and is not complaining about operations taking too long?

This is a problem we have faced when we have network-attached storage. Please verify.

**Comment by raviranjanelastisys** [comment]
@llarsson Sure Lars , noted with thanks . Will update about the etcd performance asap

We have completed the terraform scripts and were able to launch the k8s cluster using kubespray . Blog creation in progress

**Comment by raviranjanelastisys** [comment]
<img width="766" alt="etcd_performance_SSD" src="https://user-images.githubusercontent.com/75951259/115854139-9555e600-a447-11eb-843a-ce1f87c09f91.PNG">

99th percentile of fdatasync durations is 8.029ms which is < than 10ms - Which should be considered the storage is fast enough.

**Comment by raviranjanelastisys** [comment]
Roadblock - Had a detail technical discussion with IONOS cloud architect team , but seems like they will not make the CCM as a open source for us to dynamically provision the Load Balancer and Storage . They had tried to make it open-source in the past but no luck . However , IONOS team have taken our inputs as a  buisness case and will check internally with management  , if there is any possibilities to make CCM as a open source being elastisys as a partner to them but they highly doubt.

**Comment by OlleLarsson** [comment]
@llarsson still relevant :) ?

**Comment by llarsson** [comment]
@simonekman?

**Comment by simonekman** [comment]
@OlleLarsson @llarsson @tordsson. I would say we can pause this until further notice, IONOS support will not be relevant for many months. At the moment we should focus on adding support for one more cloud and that will likely be UpCloud. That means we have no real need for IONOS until we want to hire sales people in Germany and I don't see that happening any time soon.
