### ISSUE TITLE
Integrate conformance testing in the release process

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-kubespray#71]
When we release a new version of compliantkubernetes-kubespray, we should check if the k8s version has been bumped to a new minor version (0.x.0) in which case we should run the conformante tests and submit the results. Theay are pretty straightforward and the process can be automated to a large extent.

https://github.com/cncf/k8s-conformance/blob/master/instructions.md

**Comment by tordsson** [comment]
Once done, ask kubespray community if they want this upstreamed.
