### ISSUE TITLE
Smoothen Kubespray OpenStack

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#72]
**Describe the bug**

The current [CK8s on OpenStack documentation](https://compliantkubernetes.io/operator-manual/openstack/) says:

```
!!!warning
    The above will not work well if you are using a bastion host.
    This is due to [some hard coded paths](https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/openstack/modules/compute/main.tf#L207).
```

Let's figure out a way to either fix this upstream or make Kubespray usage easier for us. Related to https://github.com/elastisys/compliantkubernetes/issues/92

**NOTE**

If this task feels fuzzy, it's because it is. I'm putting it here so we can track it. Likely it will become clearer what needs to be done once https://github.com/elastisys/compliantkubernetes/issues/92 is complete.

**Comment by crssnd** [comment]
@cristiklein we can decide fixing upstream kubespray issues only when we need it.
I will close this issue.
