### ISSUE TITLE
Replace PodSecurityPolicies

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#74]
**What should be investigated.**

PodSecurityPolicies are planned to be [deprecated in Kubernetes 1.21 and removed in Kubernetes 1.25](https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies).

**UPDATE 2021-11-26**: [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) are now officially supported and documented. They allow putting namespaces in the [baseline](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/security/podsecurity-baseline.yaml), restricted or privileged security profiles.

Privileged seems to be what we need for "system" Pods, e.g., fluentd, falco.

Baseline seems to be what we need for "application" and user Pods, e.g., Harbor, Elasticsearch, Kibana.

**What artifacts should this produce.**

* A demo of the future approach that solves the problems that PodSecurityPolicies currently do.
* Action items to migrate to Pod Security Standards

**Comment by crssnd** [comment]
we will go with gatekeeper as a PSP replacement.
more specific issues will be opened
