### ISSUE TITLE
Avoid installing things on localhost as part of apply

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#78]
During today's task force meeting it was suggested that we should avoid doing things like automatically installing dependencies as part of "apply". To stick to POLA, we should instead document what dependencies there are and possibly provide a separate way of installing them. Apply should just "do its thing".

The ck8s-devbox was also suggested as a "replacement" of the automatic installation of dependencies, since it could contain all the dependencies in the pre-baked image.

This issue would be a natural next step from https://github.com/elastisys/compliantkubernetes-kubespray/pull/76.

Related issue: #77. Please note that #77 is about *adding* docs/dependencies that are not there today, whereas this issue is about *changing* how we handle dependencies that we already have included today.

**Comment by Xartos** [comment]
Closing this because this isn't as big of an issue anymore since we have the devbox and use venv for *almost* everything
