### ISSUE TITLE
[1] Vendor upstream charts

### ISSUE THREAD

**Issue by simonklb** [elastisys/compliantkubernetes-kubespray#82]
**Is your feature request related to a problem? Please describe.**
We're currently moving towards vendoring upstream charts.
See: https://github.com/elastisys/compliantkubernetes-apps/pull/444

We should do the same in this repository. Specifically [rook](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/rook/deploy-rook.sh#L7).

**Describe the solution you'd like**

Vendor upstream charts.

**Comment by aarnq** [comment]
This was completed with https://github.com/elastisys/compliantkubernetes-kubespray/pull/284
