### ISSUE TITLE
[2] Check possibility to migrate from kubespray 2.15.0 -> 2.16.0

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-kubespray#84]
**What should be investigated.**

If we can migrate from kubespray 2.15.0 -> 2.16.0 and if there are any manual steps that are needed (like changing name of some variables or so)

Notable change is that the group `kube-masters` are now called `kube_control_planel`

**What artifacts should this produce.**

Document that describes the upgrade process

**Comment by Xartos** [comment]
Note that the inventory is different for openstack (dynamic script) and exoscale (static file). Therefore we would need to test this on both to make sure we cover all cases

**Comment by cristiklein** [comment]
Related: #80
