### ISSUE TITLE
[1] Add automatic release/better release flow

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-kubespray#90]
**Is your feature request related to a problem? Please describe.**

In [compliantkubernetes-apps](https://github.com/elastisys/compliantkubernetes-apps) there's quite good automation for releases and similar. We should do the same here as well.

**Describe the solution you'd like**

We could probably re-use a lot of the actions from apps and tweak it to fit here.

**Describe alternatives you've considered**

Not having this release flow.

**Additional context**

**Definition of done:**

When there's similar process of releaseing a version here compared to [compliantkubernetes-apps](https://github.com/elastisys/compliantkubernetes-apps)

**Comment by tordsson** [comment]
Do as part of next release, as we are upgrading kubespray to 2.16 then...
