### ISSUE TITLE
[5] Update default config to use external openstack controller instead of in-tree and test migration path

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-kubespray#91]
**Is your feature request related to a problem? Please describe.**
We are using the deprecated in-tree openstack cloud controller by default: https://github.com/elastisys/compliantkubernetes-kubespray/blob/90914b57dc3f34adb6b948a8966a6811f4dc3401/config/openstack/group_vars/k8s-cluster/ck8s-k8s-cluster-openstack.yaml#L3

**Describe the solution you'd like**
Switch to the external openstack controller. Also test that a migration works and document such a migration. Kubespray has support for the external cloud provider:
https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6a085ac99e076b51d314fcf76e4127b4/inventory/sample/group_vars/all/all.yml#L56-L59
https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6a085ac99e076b51d314fcf76e4127b4/inventory/sample/group_vars/all/openstack.yml#L18

Test that both cinder volumes and service loadbalancers transfer without issue.

**Describe alternatives you've considered**
The only other option is to not have cloud controller integration when the in-tree support is removed, this is not acceptable.

**Additional context**

**Definition of done:**
- Default openstack config uses external cloud controller.
- A documented migration path exists
- Public documentation is updated (and should include how to enable support for service loadbalancers)

**Comment by cristiklein** [comment]
Copy-paste-adapt from Slack.

IIRC, SafeSpring's old environment only worked with the in-tree OpenStack provider. The out-of-tree OpenStack provider needs Cinder v3, while only Cinder v2 was available in their old environment.

Relevant links:
* Comment from upstream saying that the out-of-tree provider will not support Cinder v2: https://github.com/kubernetes/cloud-provider-openstack/issues/1059#issuecomment-628496968
* Code that shows out-of-tree provider dealing only with Cinder v3: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack.go#L162
* Code that shows in-tree provider dealing with Cinder v1, v2 and v3: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go#L871

**Comment by tordsson** [comment]
In-tree support to be deprecated in k8s 1.21 (or was it 1.22?)
