### ISSUE TITLE
[3] Make it easy to use OpenID

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#92]
**Is your feature request related to a problem? Please describe.**

This repo currently encourages using cluster-admin credentials. This is not okay with certain regulations, and in those cases operators need to manually set up OpenID in KUBECONFIG.

Let us make it easy to use OpenID.

**Describe the solution you'd like**

`${CK8S_CONFIG_PATH}/.state` contains a KUBECONFIG which only has OpenID configuration. This config should be un-encrypted, since we determined that the OpenID client secret is not valuable.

**Additional context:**

- Might be a good opportunity to align with [ADR-0006 "Use Standard Kubeconfig Mechanisms"](https://compliantkubernetes.io/adr/0006-use-standard-kubeconfig-mechanisms/).

**Definition of done:**

- Compliant Kubernetes Kubespray makes it easy to generate a KUBECONFIG with OpenID.
- Compliant Kubernetes apps makes it easy to consume a KUBECONFIG with OpenID.
- Documentation to achieve the above is clear and easy to access.

**Comment by viktor-f** [comment]
I agree with the general idea. But just wanted to remind us that we install dex as part of ckompliantkubernetes-apps, so a kubeconfig with OpenID will not be usable until a part of the compliantkubernetes-apps installation is done.

**Comment by cristiklein** [comment]
@viktor-f Indeed, it is a bit of a chicken-and-egg. I see two solutions to this:

1. Configure the SC with Google OpenID directly. We would not get group claims, but it might be worth living with this limitation.
2. Run `helm install ... dex` from a master of the SC. Kubespray already supports installing [Helm on the masters](https://github.com/kubernetes-sigs/kubespray/blob/14cf3e138b4aa2e268c7328cf045be291ccbe548/inventory/sample/group_vars/k8s_cluster/addons.yml#L7).

**Comment by cristiklein** [comment]
One more comment, please check if we can use public clients, to avoid strong the OpenID client secret.

- https://dexidp.io/docs/custom-scopes-claims-clients/#public-clients

**Comment by Xartos** [comment]
> One more comment, please check if we can use public clients, to avoid strong the OpenID client secret.
> 
>     * https://dexidp.io/docs/custom-scopes-claims-clients/#public-clients

Seems like kubelogin doesn't support "secret free" auth flows https://github.com/int128/kubelogin/blob/master/docs/usage.md#authentication-flows

So I guess we just need to count the client secret as a non secret

**Comment by raviranjanelastisys** [comment]
This is implemented , closing now
